/**
 * Single source of truth for the public site's static imagery.
 *
 * - `plate.*` and the product concepts are conceptual PRODUCT RENDERS
 *   generated by tools/renders (node tools/renders/build.mjs).
 * - `photo.*` are the real photographs that ship with the project.
 *
 * To replace any of them with a final photograph, drop the new WebP files
 * at the same paths (or change the paths here) — no Vue changes needed.
 * Pending photography is listed with exact prompts in PROMPTS-IMAGES.md.
 */

export type MediaImage = {
    src: string;
    srcset?: string;
    width: number;
    height: number;
    alt: string;
};

const plate = (
    name: string,
    widths: number[],
    ratio: number,
    alt: string,
): MediaImage => {
    const largest = Math.max(...widths);

    return {
        src: `/media/brand/plate/legacy-plate-${name}-${largest}.webp`,
        srcset: widths
            .map(
                (w) =>
                    `/media/brand/plate/legacy-plate-${name}-${w}.webp ${w}w`,
            )
            .join(', '),
        width: largest,
        height: Math.round(largest / ratio),
        alt,
    };
};

export const MEDIA = {
    plate: {
        hero: plate(
            'hero',
            [800, 1200, 1800],
            1.5,
            'Legacy Plate de Zamak niquelado sobre piedra oscura, con datos del atleta y panel negro con el monograma FL',
        ),
        portrait: plate(
            'portrait',
            [640, 1000],
            1000 / 1400,
            'Legacy Plate personalizada sobre piedra oscura',
        ),
        float: plate(
            'float',
            [700, 1200],
            1200 / 700,
            'Legacy Plate personalizada con nombre, evento, distancia y tiempo',
        ),
        front: plate(
            'front',
            [800, 1600],
            2,
            'Frente de la Legacy Plate: datos del atleta protegidos con resina y panel negro con monograma FL',
        ),
        back: plate(
            'back',
            [800, 1600],
            2,
            'Reverso de la Legacy Plate: datos del evento impresos sobre fondo negro',
        ),
        macro: plate(
            'macro',
            [600, 900, 1400],
            1,
            'Detalle del borde metálico de Zamak y la profundidad del acabado en resina',
        ),
        nfc: plate(
            'nfc',
            [600, 900, 1400],
            1,
            'La Legacy Plate acercándose a un teléfono: el NFC abre el Legacy del atleta',
        ),
        exploded: plate(
            'exploded',
            [800, 1200, 1800],
            1.2,
            'Vista explotada de la Legacy Plate: resina y gráfica, inlay NFC, ferrita anti-metal y cuerpo de Zamak niquelado',
        ),
    },
    photo: {
        celebration: {
            src: '/media/home/story/medal-closeup-667.webp',
            srcset: '/media/home/story/medal-closeup-640.webp 640w, /media/home/story/medal-closeup-667.webp 667w',
            width: 667,
            height: 1000,
            alt: 'Atleta celebrando al cruzar la meta, con su dorsal y su medalla',
        },
        triumph: {
            src: '/media/home/final/legacy-final-poster-1000.webp',
            srcset: '/media/home/final/legacy-final-poster-640.webp 640w, /media/home/final/legacy-final-poster-1000.webp 1000w',
            width: 1000,
            height: 667,
            alt: 'Atleta con los brazos en alto y la medalla al cuello',
        },
        cyclist: {
            src: '/media/home/story/finish-emotion-1000.webp',
            srcset: '/media/home/story/finish-emotion-640.webp 640w, /media/home/story/finish-emotion-1000.webp 1000w',
            width: 1000,
            height: 667,
            alt: 'Triatleta en bicicleta de contrarreloj bajo la lluvia',
        },
        runner: {
            src: '/media/home/story/race-effort-1000.webp',
            srcset: '/media/home/story/race-effort-640.webp 640w, /media/home/story/race-effort-1000.webp 1000w',
            width: 1000,
            height: 667,
            alt: 'Corredora en plena zancada con iluminación dramática',
        },
        dawn: {
            src: '/media/home/story/training-dawn-1000.webp',
            srcset: '/media/home/story/training-dawn-640.webp 640w, /media/home/story/training-dawn-1000.webp 1000w',
            width: 1000,
            height: 1000,
            alt: 'Corredora entrenando junto al mar al amanecer',
        },
        start: {
            src: '/media/home/hero/finisher-hero-poster.webp',
            srcset: '/media/home/hero/finisher-hero-poster-mobile.webp 750w, /media/home/hero/finisher-hero-poster.webp 1280w',
            width: 1280,
            height: 720,
            alt: 'Tres atletas en la línea de salida de una pista',
        },
    },
} satisfies {
    plate: Record<string, MediaImage>;
    photo: Record<string, MediaImage>;
};
