import {
    AlertTriangle,
    Award,
    Boxes,
    Building2,
    Calendar,
    CalendarDays,
    ClipboardList,
    Compass,
    Cpu,
    CreditCard,
    Database,
    Factory,
    Flag,
    History,
    Image,
    KeyRound,
    LayoutGrid,
    LayoutTemplate,
    Package,
    Palette,
    Plug,
    QrCode,
    Receipt,
    Settings,
    Settings2,
    ShieldCheck,
    ShieldQuestion,
    ShoppingBag,
    ShoppingCart,
    Ticket,
    Trophy,
    UserCheck,
    UserCircle,
    UserCog,
    Users,
    Upload,
    Warehouse,
    Zap,
} from '@lucide/vue';
import type { LucideIcon } from '@lucide/vue';

/**
 * Maps the icon name strings stored in config/permissions.php / navigation.ts
 * (plain strings, since PHP can't reference Vue components) to the actual Lucide
 * component — one lookup shared by the roles permission matrix and the app-wide
 * sidebar/command menu, so both read the same icon for the same module.
 */
const iconMap: Record<string, LucideIcon> = {
    AlertTriangle,
    Award,
    Boxes,
    Building2,
    Calendar,
    CalendarDays,
    ClipboardList,
    Compass,
    Cpu,
    CreditCard,
    Database,
    Factory,
    Flag,
    History,
    Image,
    KeyRound,
    LayoutGrid,
    LayoutTemplate,
    Package,
    Palette,
    Plug,
    QrCode,
    Receipt,
    Settings,
    Settings2,
    ShieldCheck,
    ShieldQuestion,
    ShoppingBag,
    ShoppingCart,
    Ticket,
    Trophy,
    UserCheck,
    UserCircle,
    UserCog,
    Users,
    Upload,
    Warehouse,
    Zap,
};

export function resolveIcon(name: string): LucideIcon {
    return iconMap[name] ?? Boxes;
}
